var httpCall=require("./httpCall");
var db=require("../dbmodule/dj");
var config=require("../config");
module.exports.init=function(){
	var url=config.apiBaseUrl;
	// url+="/search?access_token="+config.access_token;
	// urlConfiguration(url);
	for(var i=0;i<tokenArray.length;i++){
		urlConfiguration(url+"/search?access_token="+tokenArray[i],i,707);
	}
}
function combineArray(array){

}
var tokenArray=[
"EAACEdEose0cBAO8xdXFhF0Qvt4juTRUDKEgkR4MBAyIbMcH13JwqT1jb1qpLJOIugm1Na0QiWvjnFFW7OpxBt6M9xEXJirc5Mb79EfGAkQEZBy8MCpaJBJVAruooeZAahxdD0sufl8YgQAGywdsbg5MRMszYHywj41HVeDZAQZDZD"];

var array2=[
"Nightlife",
"Night Club",
"Dance Club",
"Jazz Club",
"Pubs",
"gastropubs",
"Disco",
"Lounge",
"Karaoke",
"Party Center",
"Bars",
"Sports Bar",
"Dance Bar",
"Gay Bar",
"Bar & Grill",
"Theatre",
"Arts/Entertainment/Nightlife",
"Performance venue",
"Events Creaters",
"Event Planner",
"Entertainment service",
"Event Management",
"Nightlife Delhi",
"Club Delhi",
"Club banglo",
"Club Goa",
"Club chandig",
"Club Chennai",
"Club gurgaon",
"Club mumbai",
"club kolka",
"Pub mumbai",
"Pub Delhi",
"pub chandi",
"pub gurgaon",
"pub noida",
"pub Chennai",
"pub banglore",
"pub kolka",
"gastropubs Delhi",
"Disco Delhi",
"Lounge Delhi",
"Karaoke Delhi",
"Party Center Delhi",
"Sports Bar Delhi",
"Dance Bar Delhi",
"Gay Bar Delhi",
"Bar & Grill Delhi",
"Theatre Delhi",
"Arts/Entertainment/Nightlife Delhi",
"Performance venue Delhi",
"Nightlife Mumbai",
"Night Club Mumbai",
"Dance Club Mumbai",
"Jazz Club Mumbai",
"Pubs Mumbai",
"gastropubs Mumbai",
"Disco Mumbai",
"Lounge Mumbai",
"Karaoke Mumbai",
"Party Center Mumbai",
"Bars Mumbai",
"Sports Bar Mumbai",
"Dance Bar Mumbai",
"Gay Bar Mumbai",
"Bar & Grill Mumbai",
"Theatre Mumbai",
"Arts/Entertainment/Nightlife Mumbai",
"Performance venue Mumbai",
"Nightlife Bangalore",
"Night Club Bangalore",
"Dance Club Bangalore",
"Jazz Club Bangalore",
"Pubs Bangalore",
"gastropubs Bangalore",
"Disco Bangalore",
"Lounge Bangalore",
"Karaoke Bangalore",
"Party Center Bangalore",
"Bars Bangalore",
"Sports Bar Bangalore",
"Dance Bar Bangalore",
"Gay Bar Bangalore",
"Bar & Grill Bangalore",
"Theatre Bangalore",
"Arts/Entertainment/Nightlife Bangalore",
"Performance venue Bangalore",
"Nightlife Pune",
"Night Club Pune",
"Dance Club Pune",
"Jazz Club Pune",
"Pubs Pune",
"gastropubs Pune",
"Disco Pune",
"Lounge Pune",
"Karaoke Pune",
"Party Center Pune",
"Bars Pune",
"Sports Bar Pune",
"Dance Bar Pune",
"Gay Bar Pune",
"Bar & Grill Pune",
"Theatre Pune",
"Arts/Entertainment/Nightlife Pune",
"Performance venue Pune",
"Nightlife Chandigarh",
"Night Club Chandigarh",
"Dance Club Chandigarh",
"Jazz Club Chandigarh",
"Pubs Chandigarh",
"gastropubs Chandigarh",
"Disco Chandigarh",
"Lounge Chandigarh",
"Karaoke Chandigarh",
"Party Center Chandigarh",
"Bars Chandigarh",
"Sports Bar Chandigarh",
"Dance Bar Chandigarh",
"Gay Bar Chandigarh",
"Bar & Grill Chandigarh",
"Theatre Chandigarh",
"Arts/Entertainment/Nightlife Chandigarh",
"Performance venue Chandigarh",
"Nightlife Goa",
"Night Club Goa",
"Dance Club Goa",
"Jazz Club Goa",
"Pubs Goa",
"gastropubs Goa",
"Disco Goa",
"Lounge Goa",
"Karaoke Goa",
"Party Center Goa",
"Bars Goa",
"Sports Bar Goa",
"Dance Bar Goa",
"Gay Bar Goa",
"Bar & Grill Goa",
"Theatre Goa",
"Arts/Entertainment/Nightlife Goa",
"Performance venue Goa",
"Nightlife Hyderabad",
"Night Club Hyderabad",
"Dance Club Hyderabad",
"Jazz Club Hyderabad",
"Pubs Hyderabad",
"gastropubs Hyderabad",
"Disco Hyderabad",
"Lounge Hyderabad",
"Karaoke Hyderabad",
"Party Center Hyderabad",
"Bars Hyderabad",
"Sports Bar Hyderabad",
"Dance Bar Hyderabad",
"Gay Bar Hyderabad",
"Bar & Grill Hyderabad",
"Theatre Hyderabad",
"Arts/Entertainment/Nightlife Hyderabad",
"Performance venue Hyderabad",
"Nightlife Chennai",
"Night Club Chennai",
"Dance Club Chennai",
"Jazz Club Chennai",
"Pubs Chennai",
"gastropubs Chennai",
"Disco Chennai",
"Lounge Chennai",
"Karaoke Chennai",
"Party Center Chennai",
"Bars Chennai",
"Sports Bar Chennai",
"Dance Bar Chennai",
"Gay Bar Chennai",
"Bar & Grill Chennai",
"Theatre Chennai",
"Arts/Entertainment/Nightlife Chennai",
"Performance venue Chennai",
"Nightlife Kolkata",
"Night Club Kolkata",
"Dance Club Kolkata",
"Jazz Club Kolkata",
"Pubs Kolkata",
"gastropubs Kolkata",
"Disco Kolkata",
"Lounge Kolkata",
"Karaoke Kolkata",
"Party Center Kolkata",
"Bars Kolkata",
"Sports Bar Kolkata",
"Dance Bar Kolkata",
"Gay Bar Kolkata",
"Bar & Grill Kolkata",
"Theatre Kolkata",
"Arts/Entertainment/Nightlife Kolkata",
"Performance venue Kolkata",
"Musician/Band",
"Musician",
"Band",
"DJ",
"Artist",
"Singer",
"Public Figure",
"Entertainer",
"Producer",
"Dancer",
"Performing Artists",
"All-female band",
"Big band",
"Boy band",
"Christian band",
"Church band",
"Concert band",
"Cover band",
"Dansband",
"Fife and drum Band",
"Garage rock band",
"Girl group Band",
"Family band",
"Jam band",
"Jazz band",
"Jug band",
"Klezmer band",
"Marching band",
"Military band",
"Orchestra",
"Organ trio",
"Rock band",
"Rock Supergroup",
"School band",
"Marching band",
"Ska band",
"Tribute act",
"Worship band",
"Breaks DJ",
"Chill Out DJ",
"Drum & Bass DJ",
"Dubstep DJ",
"Electro House DJ",
"Electronica DJ",
"Funk/R&B DJ",
"Hard Dance DJ",
"Hardcore/Hard Techno DJ",
"Hip-Hop DJ",
"House DJ",
"IndieDance/NuDisco DJ",
"Minimal DJ",
"Open Format DJ",
"Progressive House DJ",
"Psy-Trance DJ",
"Reggae/Dub DJ",
"Tech House DJ",
"Techno DJ",
"Trance DJ",
"Trap DJ",
"Blues music",
"Classical music",
"Country music",
"Dance music",
"Electronic music",
"Gospel music",
"Heavy metal music",
"Hip hop music",
"Jazz music",
"Music videos",
"Pop music",
"Rhythm and blues music",
"Rock music",
"Soul music",
"Musician/Band Delhi",
"Musician Delhi",
"Band Delhi",
"DJ Delhi",
"Artist Delhi",
"Singer Delhi",
"Public Figure Delhi",
"Entertainer Delhi",
"Producer Delhi",
"Dancer Delhi",
"Performing Artists Delhi",
"All-female band Delhi",
"Big band Delhi",
"Boy band Delhi",
"Christian band Delhi",
"Church band Delhi",
"Concert band Delhi",
"Cover band Delhi",
"Dansband Delhi",
"Fife and drum Band Delhi",
"Garage rock band Delhi",
"Girl group Band Delhi",
"Family band Delhi",
"Jam band Delhi",
"Jazz band Delhi",
"Jug band Delhi",
"Klezmer band Delhi",
"Marching band Delhi",
"Military band Delhi",
"Orchestra Delhi",
"Organ trio Delhi",
"Rock band Delhi",
"Rock Supergroup Delhi",
"School band Delhi",
"Marching band Delhi",
"Ska band Delhi",
"Tribute act Delhi",
"Worship band Delhi",
"Breaks DJ Delhi",
"Chill Out DJ Delhi",
"Drum & Bass DJ Delhi",
"Dubstep DJ Delhi",
"Electro House DJ Delhi",
"Electronica DJ Delhi",
"Funk/R&B DJ Delhi",
"Hard Dance DJ Delhi",
"Hardcore/Hard Techno DJ Delhi",
"Hip-Hop DJ Delhi",
"House DJ Delhi",
"IndieDance/NuDisco DJ Delhi",
"Minimal DJ Delhi",
"Open Format DJ Delhi",
"Progressive House DJ Delhi",
"Psy-Trance DJ Delhi",
"Reggae/Dub DJ Delhi",
"Tech House DJ Delhi",
"Techno DJ Delhi",
"Trance DJ Delhi",
"Trap DJ Delhi",
"Blues music Delhi",
"Classical music Delhi",
"Country music Delhi",
"Dance music Delhi",
"Electronic music Delhi",
"Gospel music Delhi",
"Heavy metal music Delhi",
"Hip hop music Delhi",
"Jazz music Delhi",
"Music videos Delhi",
"Pop music Delhi",
"Rhythm and blues music Delhi",
"Rock music Delhi",
"Soul music Delhi",
"Musician/Band Mumbai",
"Musician Mumbai",
"Band Mumbai",
"DJ Mumbai",
"Artist Mumbai",
"Singer Mumbai",
"Public Figure Mumbai",
"Entertainer Mumbai",
"Producer Mumbai",
"Dancer Mumbai",
"Performing Artists Mumbai",
"All-female band Mumbai",
"Big band Mumbai",
"Boy band Mumbai",
"Christian band Mumbai",
"Church band Mumbai",
"Concert band Mumbai",
"Cover band Mumbai",
"Dansband Mumbai",
"Fife and drum Band Mumbai",
"Garage rock band Mumbai",
"Girl group Band Mumbai",
"Family band Mumbai",
"Jam band Mumbai",
"Jazz band Mumbai",
"Jug band Mumbai",
"Klezmer band Mumbai",
"Marching band Mumbai",
"Military band Mumbai",
"Orchestra Mumbai",
"Organ trio Mumbai",
"Rock band Mumbai",
"Rock Supergroup Mumbai",
"School band Mumbai",
"Marching band Mumbai",
"Ska band Mumbai",
"Tribute act Mumbai",
"Worship band Mumbai",
"Breaks DJ Mumbai",
"Chill Out DJ Mumbai",
"Drum & Bass DJ Mumbai",
"Dubstep DJ Mumbai",
"Electro House DJ Mumbai",
"Electronica DJ Mumbai",
"Funk/R&B DJ Mumbai",
"Hard Dance DJ Mumbai",
"Hardcore/Hard Techno DJ Mumbai",
"Hip-Hop DJ Mumbai",
"House DJ Mumbai",
"IndieDance/NuDisco DJ Mumbai",
"Minimal DJ Mumbai",
"Open Format DJ Mumbai",
"Progressive House DJ Mumbai",
"Psy-Trance DJ Mumbai",
"Reggae/Dub DJ Mumbai",
"Tech House DJ Mumbai",
"Techno DJ Mumbai",
"Trance DJ Mumbai",
"Trap DJ Mumbai",
"Blues music Mumbai",
"Classical music Mumbai",
"Country music Mumbai",
"Dance music Mumbai",
"Electronic music Mumbai",
"Gospel music Mumbai",
"Heavy metal music Mumbai",
"Hip hop music Mumbai",
"Jazz music Mumbai",
"Music videos Mumbai",
"Pop music Mumbai",
"Rhythm and blues music Mumbai",
"Rock music Mumbai",
"Soul music Mumbai",
"Musician/Band Bangalore",
"Musician Bangalore",
"Band Bangalore",
"DJ Bangalore",
"Artist Bangalore",
"Singer Bangalore",
"Public Figure Bangalore",
"Entertainer Bangalore",
"Producer Bangalore",
"Dancer Bangalore",
"Performing Artists Bangalore",
"All-female band Bangalore",
"Big band Bangalore",
"Boy band Bangalore",
"Christian band Bangalore",
"Church band Bangalore",
"Concert band Bangalore",
"Cover band Bangalore",
"Dansband Bangalore",
"Fife and drum Band Bangalore",
"Garage rock band Bangalore",
"Girl group Band Bangalore",
"Family band Bangalore",
"Jam band Bangalore",
"Jazz band Bangalore",
"Jug band Bangalore",
"Klezmer band Bangalore",
"Marching band Bangalore",
"Military band Bangalore",
"Orchestra Bangalore",
"Organ trio Bangalore",
"Rock band Bangalore",
"Rock Supergroup Bangalore",
"School band Bangalore",
"Marching band Bangalore",
"Ska band Bangalore",
"Tribute act Bangalore",
"Worship band Bangalore",
"Breaks DJ Bangalore",
"Chill Out DJ Bangalore",
"Drum & Bass DJ Bangalore",
"Dubstep DJ Bangalore",
"Electro House DJ Bangalore",
"Electronica DJ Bangalore",
"Funk/R&B DJ Bangalore",
"Hard Dance DJ Bangalore",
"Hardcore/Hard Techno DJ Bangalore",
"Hip-Hop DJ Bangalore",
"House DJ Bangalore",
"IndieDance/NuDisco DJ Bangalore",
"Minimal DJ Bangalore",
"Open Format DJ Bangalore",
"Progressive House DJ Bangalore",
"Psy-Trance DJ Bangalore",
"Reggae/Dub DJ Bangalore",
"Tech House DJ Bangalore",
"Techno DJ Bangalore",
"Trance DJ Bangalore",
"Trap DJ Bangalore",
"Blues music Bangalore",
"Classical music Bangalore",
"Country music Bangalore",
"Dance music Bangalore",
"Electronic music Bangalore",
"Gospel music Bangalore",
"Heavy metal music Bangalore",
"Hip hop music Bangalore",
"Jazz music Bangalore",
"Music videos Bangalore",
"Pop music Bangalore",
"Rhythm and blues music Bangalore",
"Rock music Bangalore",
"Soul music Bangalore",
"Musician/Band Pune",
"Musician Pune",
"Band Pune",
"DJ Pune",
"Artist Pune",
"Singer Pune",
"Public Figure Pune",
"Entertainer Pune",
"Producer Pune",
"Dancer Pune",
"Performing Artists Pune",
"All-female band Pune",
"Big band Pune",
"Boy band Pune",
"Christian band Pune",
"Church band Pune",
"Concert band Pune",
"Cover band Pune",
"Dansband Pune",
"Fife and drum Band Pune",
"Garage rock band Pune",
"Girl group Band Pune",
"Family band Pune",
"Jam band Pune",
"Jazz band Pune",
"Jug band Pune",
"Klezmer band Pune",
"Marching band Pune",
"Military band Pune",
"Orchestra Pune",
"Organ trio Pune",
"Rock band Pune",
"Rock Supergroup Pune",
"School band Pune",
"Marching band Pune",
"Ska band Pune",
"Tribute act Pune",
"Worship band Pune",
"Breaks DJ Pune",
"Chill Out DJ Pune",
"Drum & Bass DJ Pune",
"Dubstep DJ Pune",
"Electro House DJ Pune",
"Electronica DJ Pune",
"Funk/R&B DJ Pune",
"Hard Dance DJ Pune",
"Hardcore/Hard Techno DJ Pune",
"Hip-Hop DJ Pune",
"House DJ Pune",
"IndieDance/NuDisco DJ Pune",
"Minimal DJ Pune",
"Open Format DJ Pune",
"Progressive House DJ Pune",
"Psy-Trance DJ Pune",
"Reggae/Dub DJ Pune",
"Tech House DJ Pune",
"Techno DJ Pune",
"Trance DJ Pune",
"Trap DJ Pune",
"Blues music Pune",
"Classical music Pune",
"Country music Pune",
"Dance music Pune",
"Electronic music Pune",
"Gospel music Pune",
"Heavy metal music Pune",
"Hip hop music Pune",
"Jazz music Pune",
"Music videos Pune",
"Pop music Pune",
"Rhythm and blues music Pune",
"Rock music Pune",
"Soul music Pune",
"Musician/Band Chandigarh",
"Musician Chandigarh",
"Band Chandigarh",
"DJ Chandigarh",
"Artist Chandigarh",
"Singer Chandigarh",
"Public Figure Chandigarh",
"Entertainer Chandigarh",
"Producer Chandigarh",
"Dancer Chandigarh",
"Performing Artists Chandigarh",
"All-female band Chandigarh",
"Big band Chandigarh",
"Boy band Chandigarh",
"Christian band Chandigarh",
"Church band Chandigarh",
"Concert band Chandigarh",
"Cover band Chandigarh",
"Dansband Chandigarh",
"Fife and drum Band Chandigarh",
"Garage rock band Chandigarh",
"Girl group Band Chandigarh",
"Family band Chandigarh",
"Jam band Chandigarh",
"Jazz band Chandigarh",
"Jug band Chandigarh",
"Klezmer band Chandigarh",
"Marching band Chandigarh",
"Military band Chandigarh",
"Orchestra Chandigarh",
"Organ trio Chandigarh",
"Rock band Chandigarh",
"Rock Supergroup Chandigarh",
"School band Chandigarh",
"Marching band Chandigarh",
"Ska band Chandigarh",
"Tribute act Chandigarh",
"Worship band Chandigarh",
"Breaks DJ Chandigarh",
"Chill Out DJ Chandigarh",
"Drum & Bass DJ Chandigarh",
"Dubstep DJ Chandigarh",
"Electro House DJ Chandigarh",
"Electronica DJ Chandigarh",
"Funk/R&B DJ Chandigarh",
"Hard Dance DJ Chandigarh",
"Hardcore/Hard Techno DJ Chandigarh",
"Hip-Hop DJ Chandigarh",
"House DJ Chandigarh",
"IndieDance/NuDisco DJ Chandigarh",
"Minimal DJ Chandigarh",
"Open Format DJ Chandigarh",
"Progressive House DJ Chandigarh",
"Psy-Trance DJ Chandigarh",
"Reggae/Dub DJ Chandigarh",
"Tech House DJ Chandigarh",
"Techno DJ Chandigarh",
"Trance DJ Chandigarh",
"Trap DJ Chandigarh",
"Blues music Chandigarh",
"Classical music Chandigarh",
"Country music Chandigarh",
"Dance music Chandigarh",
"Electronic music Chandigarh",
"Gospel music Chandigarh",
"Heavy metal music Chandigarh",
"Hip hop music Chandigarh",
"Jazz music Chandigarh",
"Music videos Chandigarh",
"Pop music Chandigarh",
"Rhythm and blues music Chandigarh",
"Rock music Chandigarh",
"Soul music Chandigarh",
"Musician/Band Goa",
"Musician Goa",
"Band Goa",
"DJ Goa",
"Artist Goa",
"Singer Goa",
"Public Figure Goa",
"Entertainer Goa",
"Producer Goa",
"Dancer Goa",
"Performing Artists Goa",
"All-female band Goa",
"Big band Goa",
"Boy band Goa",
"Christian band Goa",
"Church band Goa",
"Concert band Goa",
"Cover band Goa",
"Dansband Goa",
"Fife and drum Band Goa",
"Garage rock band Goa",
"Girl group Band Goa",
"Family band Goa",
"Jam band Goa",
"Jazz band Goa",
"Jug band Goa",
"Klezmer band Goa",
"Marching band Goa",
"Military band Goa",
"Orchestra Goa",
"Organ trio Goa",
"Rock band Goa",
"Rock Supergroup Goa",
"School band Goa",
"Marching band Goa",
"Ska band Goa",
"Tribute act Goa",
"Worship band Goa",
"Breaks DJ Goa",
"Chill Out DJ Goa",
"Drum & Bass DJ Goa",
"Dubstep DJ Goa",
"Electro House DJ Goa",
"Electronica DJ Goa",
"Funk/R&B DJ Goa",
"Hard Dance DJ Goa",
"Hardcore/Hard Techno DJ Goa",
"Hip-Hop DJ Goa",
"House DJ Goa",
"IndieDance/NuDisco DJ Goa",
"Minimal DJ Goa",
"Open Format DJ Goa",
"Progressive House DJ Goa",
"Psy-Trance DJ Goa",
"Reggae/Dub DJ Goa",
"Tech House DJ Goa",
"Techno DJ Goa",
"Trance DJ Goa",
"Trap DJ Goa",
"Blues music Goa",
"Classical music Goa",
"Country music Goa",
"Dance music Goa",
"Electronic music Goa",
"Gospel music Goa",
"Heavy metal music Goa",
"Hip hop music Goa",
"Jazz music Goa",
"Music videos Goa",
"Pop music Goa",
"Rhythm and blues music Goa",
"Rock music Goa",
"Soul music Goa",
"Musician/Band Hyderabad",
"Musician Hyderabad",
"Band Hyderabad",
"DJ Hyderabad",
"Artist Hyderabad",
"Singer Hyderabad",
"Public Figure Hyderabad",
"Entertainer Hyderabad",
"Producer Hyderabad",
"Dancer Hyderabad",
"Performing Artists Hyderabad",
"All-female band Hyderabad",
"Big band Hyderabad",
"Boy band Hyderabad",
"Christian band Hyderabad",
"Church band Hyderabad",
"Concert band Hyderabad",
"Cover band Hyderabad",
"Dansband Hyderabad",
"Fife and drum Band Hyderabad",
"Garage rock band Hyderabad",
"Girl group Band Hyderabad",
"Family band Hyderabad",
"Jam band Hyderabad",
"Jazz band Hyderabad",
"Jug band Hyderabad",
"Klezmer band Hyderabad",
"Marching band Hyderabad",
"Military band Hyderabad",
"Orchestra Hyderabad",
"Organ trio Hyderabad",
"Rock band Hyderabad",
"Rock Supergroup Hyderabad",
"School band Hyderabad",
"Marching band Hyderabad",
"Ska band Hyderabad",
"Tribute act Hyderabad",
"Worship band Hyderabad",
"Breaks DJ Hyderabad",
"Chill Out DJ Hyderabad",
"Drum & Bass DJ Hyderabad",
"Dubstep DJ Hyderabad",
"Electro House DJ Hyderabad",
"Electronica DJ Hyderabad",
"Funk/R&B DJ Hyderabad",
"Hard Dance DJ Hyderabad",
"Hardcore/Hard Techno DJ Hyderabad",
"Hip-Hop DJ Hyderabad",
"House DJ Hyderabad",
"IndieDance/NuDisco DJ Hyderabad",
"Minimal DJ Hyderabad",
"Open Format DJ Hyderabad",
"Progressive House DJ Hyderabad",
"Psy-Trance DJ Hyderabad",
"Reggae/Dub DJ Hyderabad",
"Tech House DJ Hyderabad",
"Techno DJ Hyderabad",
"Trance DJ Hyderabad",
"Trap DJ Hyderabad",
"Blues music Hyderabad",
"Classical music Hyderabad",
"Country music Hyderabad",
"Dance music Hyderabad",
"Electronic music Hyderabad",
"Gospel music Hyderabad",
"Heavy metal music Hyderabad",
"Hip hop music Hyderabad",
"Jazz music Hyderabad",
"Music videos Hyderabad",
"Pop music Hyderabad",
"Rhythm and blues music Hyderabad",
"Rock music Hyderabad",
"Soul music Hyderabad",
"Musician/Band Chennai",
"Musician Chennai",
"Band Chennai",
"DJ Chennai",
"Artist Chennai",
"Singer Chennai",
"Public Figure Chennai",
"Entertainer Chennai",
"Producer Chennai",
"Dancer Chennai",
"Performing Artists Chennai",
"All-female band Chennai",
"Big band Chennai",
"Boy band Chennai",
"Christian band Chennai",
"Church band Chennai",
"Concert band Chennai",
"Cover band Chennai",
"Dansband Chennai",
"Fife and drum Band Chennai",
"Garage rock band Chennai",
"Girl group Band Chennai",
"Family band Chennai",
"Jam band Chennai",
"Jazz band Chennai",
"Jug band Chennai",
"Klezmer band Chennai",
"Marching band Chennai",
"Military band Chennai",
"Orchestra Chennai",
"Organ trio Chennai",
"Rock band Chennai",
"Rock Supergroup Chennai",
"School band Chennai",
"Marching band Chennai",
"Ska band Chennai",
"Tribute act Chennai",
"Worship band Chennai",
"Breaks DJ Chennai",
"Chill Out DJ Chennai",
"Drum & Bass DJ Chennai",
"Dubstep DJ Chennai",
"Electro House DJ Chennai",
"Electronica DJ Chennai",
"Funk/R&B DJ Chennai",
"Hard Dance DJ Chennai",
"Hardcore/Hard Techno DJ Chennai",
"Hip-Hop DJ Chennai",
"House DJ Chennai",
"IndieDance/NuDisco DJ Chennai",
"Minimal DJ Chennai",
"Open Format DJ Chennai",
"Progressive House DJ Chennai",
"Psy-Trance DJ Chennai",
"Reggae/Dub DJ Chennai",
"Tech House DJ Chennai",
"Techno DJ Chennai",
"Trance DJ Chennai",
"Trap DJ Chennai",
"Blues music Chennai",
"Classical music Chennai",
"Country music Chennai",
"Dance music Chennai",
"Electronic music Chennai",
"Gospel music Chennai",
"Heavy metal music Chennai",
"Hip hop music Chennai",
"Jazz music Chennai",
"Music videos Chennai",
"Pop music Chennai",
"Rhythm and blues music Chennai",
"Rock music Chennai",
"Soul music Chennai",
"Musician/Band Kolkata",
"Musician Kolkata",
"Band Kolkata",
"DJ Kolkata",
"Artist Kolkata",
"Singer Kolkata",
"Public Figure Kolkata",
"Entertainer Kolkata",
"Producer Kolkata",
"Dancer Kolkata",
"Performing Artists Kolkata",
"All-female band Kolkata",
"Big band Kolkata",
"Boy band Kolkata",
"Christian band Kolkata",
"Church band Kolkata",
"Concert band Kolkata",
"Cover band Kolkata",
"Dansband Kolkata",
"Fife and drum Band Kolkata",
"Garage rock band Kolkata",
"Girl group Band Kolkata",
"Family band Kolkata",
"Jam band Kolkata",
"Jazz band Kolkata",
"Jug band Kolkata",
"Klezmer band Kolkata",
"Marching band Kolkata",
"Military band Kolkata",
"Orchestra Kolkata",
"Organ trio Kolkata",
"Rock band Kolkata",
"Rock Supergroup Kolkata",
"School band Kolkata",
"Marching band Kolkata",
"Ska band Kolkata",
"Tribute act Kolkata",
"Worship band Kolkata",
"Breaks DJ Kolkata",
"Chill Out DJ Kolkata",
"Drum & Bass DJ Kolkata",
"Dubstep DJ Kolkata",
"Electro House DJ Kolkata",
"Electronica DJ Kolkata",
"Funk/R&B DJ Kolkata",
"Hard Dance DJ Kolkata",
"Hardcore/Hard Techno DJ Kolkata",
"Hip-Hop DJ Kolkata",
"House DJ Kolkata",
"IndieDance/NuDisco DJ Kolkata",
"Minimal DJ Kolkata",
"Open Format DJ Kolkata",
"Progressive House DJ Kolkata",
"Psy-Trance DJ Kolkata",
"Reggae/Dub DJ Kolkata",
"Tech House DJ Kolkata",
"Techno DJ Kolkata",
"Trance DJ Kolkata",
"Trap DJ Kolkata",
"Blues music Kolkata",
"Classical music Kolkata",
"Country music Kolkata",
"Dance music Kolkata",
"Electronic music Kolkata",
"Gospel music Kolkata",
"Heavy metal music Kolkata",
"Hip hop music Kolkata",
"Jazz music Kolkata",
"Music videos Kolkata",
"Pop music Kolkata",
"Rhythm and blues music Kolkata",
"Rock music Kolkata",
"Soul music Kolkata"
]

function urlConfiguration(baseUrl,tokenIndex,index){
	var query="dj";
	var type="page";
		// var url=baseUrl+"&q="+query+"&type="+type;
	// httpCallFunction(url);
	var array1=["rental","orchestra","photo","image","photographer","illusionist","magician","party planner","wedding","planner","wedding planner","variety artist","special","style makeup","makeup","style","hair style","dancer","comic artist","singer","anchor","event planner","caterers","music","pub","night","party spot","party place","night club","club","bar","lounge","ladies night","restaurant","singer","hotel","hotel"];
	//var array=['abc','bb','cd','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];
	if(index<array2.length){
		var url=baseUrl+"&q="+array2[index]+"&type=page";
		httpCallFunction(url,tokenIndex,index);
	}
	
}

function httpCallFunction(url,tokenIndex,index){
	setTimeout(httpCall.httpGetCall(url,dataParsing,tokenIndex,index),3000);
}

var count=0;

function dataParsing(array,tokenIndex,index,error){
	

	if(array.data!=undefined){
		for(var i=0;i<array.data.length;i++){
			db.saveDj(array.data[i],dbResponse);
		}
		count+=array.data.length;
		console.log("count=",count,index);
	}

	if(array.paging!=undefined&&array.paging.next!=undefined){
		httpCallFunction(array.paging.next,tokenIndex,index);
	}

	else{
		console.log("next is undefined");
		var url=config.apiBaseUrl;
		url+="/search?access_token="+tokenArray[tokenIndex];
		index++;
		urlConfiguration(url,tokenIndex,index);
	}
}

function dbResponse(result){

}